version: "3.8"
services:
  laravel:
    container_name: laravel-docker
    build: .
    volumes:
      - ./websky:/var/www/html
    ports:
      - 9000:80
  #Database server
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_DATABASE: laravel-admin
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest 
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1